//
//  MainScreenPresenter.swift
//  Tendigi
//
//  Created by Zain N. on 11/15/18.
//  Copyright (c) 2018 Mapfit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScreenPresentationLogic
{
    func formatJSON(response: MainScreen.Data.Response)
}

class MainScreenPresenter: MainScreenPresentationLogic
{
  weak var viewController: MainScreenDisplayLogic?
  
  // MARK: Do something
  
  func formatJSON(response: MainScreen.Data.Response)
  {
    
    let dateFormatterGet = DateFormatter()
    dateFormatterGet.dateFormat = "yyyy-MM-dd HH:mm:ss"
    
    let dateFormatterPrint = DateFormatter()
    dateFormatterPrint.dateFormat = "MMM dd, yyyy"
    
    var formattedTweets = [Tweet]()
    response.unformattedTweets.forEach { (tweet) in
        var newDateString = String()
        if let date = dateFormatterGet.date(from: tweet.createdAt) {
            newDateString = dateFormatterPrint.string(from: date)
        }
        formattedTweets.append(Tweet(id: tweet.id, text: tweet.text, createdAt: newDateString))
  
    }

    
    
    let viewModel = MainScreen.Data.ViewModel(formattedTweets: formattedTweets)
    viewController?.displayInformation(viewModel: viewModel)
  }
}
