//
//  MainScreenModels.swift
//  Tendigi
//
//  Created by Zain N. on 11/15/18.
//  Copyright (c) 2018 Mapfit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Tweet {
    var id: Int
    var text: String
    var createdAt: String
    
}


enum MainScreen
{
  // MARK: Use cases
  
  enum Data
  {
    struct Request
    {   
    }
    struct Response
    {
        
        var unformattedTweets: [Tweet]

    }
    struct ViewModel
    {
        var formattedTweets: [Tweet]?
        
        
    }
  }
}
