//
//  MainScreenWorker.swift
//  Tendigi
//
//  Created by Zain N. on 11/15/18.
//  Copyright (c) 2018 Mapfit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class MainScreenWorker
{
    func fetchJSONFromTendigi(completion: @escaping (_ result: MainScreen.Data.Response)->Void) {
        let tendigiURL = "http://static.tendigi.com/tweets.json"

        Alamofire.request(tendigiURL, method: .get).responseJSON { (response) in
            
            switch response.response?.statusCode {
            case 200:
                print("Successful Call")
                if let json = response.result.value {
                    let dict = json as! [[String : Any]]
                    var tweets = [Tweet]()
                    _ = dict.map { tweets.append(Tweet(id: $0["id"] as! Int, text: $0["text"] as! String, createdAt: $0["created_at"] as! String))}
                    completion(MainScreen.Data.Response(unformattedTweets: tweets))
                }
            default:
                print("unknown error code: \(response.response?.statusCode)")
            }}
    }
}
